language: java

addons:
    srcclr: true

jdk:
 - oraclejdk8

addons:
    apt:
        packages:
         - oracle-java8-installer

before_install:
 - chmod +x gradlew
after_success:
  - if [ -e ./gradlew ]; then ./gradlew codeCoverageReport;else gradle codeCoverageReport;fi
  - bash <(curl -s https://codecov.io/bash)

